name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci --no-audit --fund=false

      - name: Build
        run: npm run build

      - name: Lint (non-blocking)
        run: npm run lint -- --quiet || echo "lint errors (non-blocking)"
        continue-on-error: true

      - name: Test
        run: npm test -- --passWithNoTests
